# 2017-04-23 (cc) <paul4hough@gmail.com>

dist: trusty
language: cpp
notifications:
  email:
    - paul4hough@gmail.com

# :( unavoidable
install:
  - sudo apt-get install automake libtool
  - git clone http://github.com/pahoughton/libvalid
  - cd libvalid
  - autoreconf --install && ./configure
  - sudo make install

script:
  - autoreconf --install
  - CXXFLAGS=-std=c++11 ./configure
  - make test
