=head1 =PROJECT= Version Control

=opt nopara

Version: =VERSION=

Paul A. Houghton <paul4hough@gmail.com>

=LAST_MOD=

=opt para

=head3 Overview

All the sources for the =PROJECT= project are kept in a CVS version control
repository on &TOOLS.HOST;. This repository is currently being
maintained by Paul Houghton <paul4hough@gmail.com>, please contact
him for remote write access or any problems you encounter.  For read
only access to the repository you can use the B<cvsguest> id.

=head3 Getting The Sources from CVS

First, set your CVSROOT environment variable to:

  export CVSROOT=:pserver:cvsguest@&TOOLS.HOST;:/Tools/src/CvsRepository

Then follow the instructions in
http://&TOOLS.HOST;/Tools/VersionControl/CvsQuickRef.html to
checkout a copy of the sources using the project name of
B<lib=PROJECT=-=VER_MAJOR=>.

=for html
<hr>

=opt nopara

Paul A. Houghton <paul4hough@gmail.com>

Last Modified: =LAST_MOD=

$Id$

=opt para

=cut

$Log$
Revision 6.3  2011/12/30 23:57:07  paul
First go at Mac gcc Port

Revision 6.2  2003/09/08 15:13:23  ptpogue
change sideswipe to soundwave

Revision 6.1  2003/08/09 11:22:39  houghton
Changed to version 6

Revision 1.1  2001/07/26 19:29:01  houghton
*** empty log message ***

Revision 1.2  2000/06/11 13:21:04  houghton
Changed to refer to new CvsQuickRef page.

Revision 1.1  2000/06/04 18:01:13  houghton
Initial Version.

Revision 1.1  2000/05/31 11:20:13  houghton
Initial Version.

