ERROR tLog09.C:43 LogIf test entry.
ERROR tLog09.C:44 LogIf test entry.
TEST tLog09.C:57 LogIf test entry.
ERROR tLog09.C:61 Chunk Test:     1) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    2) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    3) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    4) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    5) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    6) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    7) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    8) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    9) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    10) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    11) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    12) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    13) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    14) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    15) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    16) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    17) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    18) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    19) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    20) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    21) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    22) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    23) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    24) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    25) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    26) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    27) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    28) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    29) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    30) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    31) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    32) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    33) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    34) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

    35) This is a large multi-line entry into the log that
    sould force an overflow becuse there are no sync
    calls.

TEST tLog09.C:79 End of Chnunk good!
TEST tLog09.C:98 End of Test
