tParam03.C:99 info message: 360 to test log trimming
tParam03.C:99 info message: 361 to test log trimming
tParam03.C:99 info message: 362 to test log trimming
tParam03.C:99 info message: 363 to test log trimming
tParam03.C:99 info message: 364 to test log trimming
tParam03.C:99 info message: 365 to test log trimming
tParam03.C:99 info message: 366 to test log trimming
tParam03.C:99 info message: 367 to test log trimming
tParam03.C:99 info message: 368 to test log trimming
tParam03.C:99 info message: 369 to test log trimming
tParam03.C:99 info message: 370 to test log trimming
tParam03.C:99 info message: 371 to test log trimming
tParam03.C:99 info message: 372 to test log trimming
tParam03.C:99 info message: 373 to test log trimming
tParam03.C:99 info message: 374 to test log trimming
tParam03.C:99 info message: 375 to test log trimming
tParam03.C:99 info message: 376 to test log trimming
tParam03.C:99 info message: 377 to test log trimming
tParam03.C:99 info message: 378 to test log trimming
tParam03.C:99 info message: 379 to test log trimming
tParam03.C:99 info message: 380 to test log trimming
tParam03.C:99 info message: 381 to test log trimming
tParam03.C:99 info message: 382 to test log trimming
tParam03.C:99 info message: 383 to test log trimming
tParam03.C:99 info message: 384 to test log trimming
tParam03.C:99 info message: 385 to test log trimming
tParam03.C:99 info message: 386 to test log trimming
tParam03.C:99 info message: 387 to test log trimming
tParam03.C:99 info message: 388 to test log trimming
tParam03.C:99 info message: 389 to test log trimming
tParam03.C:99 info message: 390 to test log trimming
tParam03.C:99 info message: 391 to test log trimming
tParam03.C:99 info message: 392 to test log trimming
tParam03.C:99 info message: 393 to test log trimming
tParam03.C:99 info message: 394 to test log trimming
tParam03.C:99 info message: 395 to test log trimming
tParam03.C:99 info message: 396 to test log trimming
tParam03.C:99 info message: 397 to test log trimming
tParam03.C:99 info message: 398 to test log trimming
tParam03.C:99 info message: 399 to test log trimming
tParam03.C:99 info message: 400 to test log trimming
tParam03.C:99 info message: 401 to test log trimming
tParam03.C:99 info message: 402 to test log trimming
tParam03.C:99 info message: 403 to test log trimming
tParam03.C:99 info message: 404 to test log trimming
tParam03.C:99 info message: 405 to test log trimming
tParam03.C:99 info message: 406 to test log trimming
tParam03.C:99 info message: 407 to test log trimming
tParam03.C:99 info message: 408 to test log trimming
tParam03.C:99 info message: 409 to test log trimming
tParam03.C:99 info message: 410 to test log trimming
tParam03.C:99 info message: 411 to test log trimming
tParam03.C:99 info message: 412 to test log trimming
tParam03.C:99 info message: 413 to test log trimming
tParam03.C:99 info message: 414 to test log trimming
tParam03.C:99 info message: 415 to test log trimming
tParam03.C:99 info message: 416 to test log trimming
tParam03.C:99 info message: 417 to test log trimming
tParam03.C:99 info message: 418 to test log trimming
tParam03.C:99 info message: 419 to test log trimming
tParam03.C:99 info message: 420 to test log trimming
tParam03.C:99 info message: 421 to test log trimming
tParam03.C:99 info message: 422 to test log trimming
tParam03.C:99 info message: 423 to test log trimming
tParam03.C:99 info message: 424 to test log trimming
tParam03.C:99 info message: 425 to test log trimming
tParam03.C:99 info message: 426 to test log trimming
tParam03.C:99 info message: 427 to test log trimming
tParam03.C:99 info message: 428 to test log trimming
tParam03.C:99 info message: 429 to test log trimming
tParam03.C:99 info message: 430 to test log trimming
tParam03.C:99 info message: 431 to test log trimming
tParam03.C:99 info message: 432 to test log trimming
tParam03.C:99 info message: 433 to test log trimming
tParam03.C:99 info message: 434 to test log trimming
tParam03.C:99 info message: 435 to test log trimming
tParam03.C:99 info message: 436 to test log trimming
tParam03.C:99 info message: 437 to test log trimming
tParam03.C:99 info message: 438 to test log trimming
tParam03.C:99 info message: 439 to test log trimming
tParam03.C:99 info message: 440 to test log trimming
tParam03.C:99 info message: 441 to test log trimming
tParam03.C:99 info message: 442 to test log trimming
tParam03.C:99 info message: 443 to test log trimming
tParam03.C:99 info message: 444 to test log trimming
tParam03.C:99 info message: 445 to test log trimming
tParam03.C:99 info message: 446 to test log trimming
tParam03.C:99 info message: 447 to test log trimming
tParam03.C:99 info message: 448 to test log trimming
tParam03.C:99 info message: 449 to test log trimming
tParam03.C:99 info message: 450 to test log trimming
tParam03.C:99 info message: 451 to test log trimming
tParam03.C:99 info message: 452 to test log trimming
tParam03.C:99 info message: 453 to test log trimming
tParam03.C:99 info message: 454 to test log trimming
tParam03.C:99 info message: 455 to test log trimming
tParam03.C:99 info message: 456 to test log trimming
tParam03.C:99 info message: 457 to test log trimming
tParam03.C:99 info message: 458 to test log trimming
tParam03.C:99 info message: 459 to test log trimming
tParam03.C:99 info message: 460 to test log trimming
tParam03.C:99 info message: 461 to test log trimming
tParam03.C:99 info message: 462 to test log trimming
tParam03.C:99 info message: 463 to test log trimming
tParam03.C:99 info message: 464 to test log trimming
tParam03.C:99 info message: 465 to test log trimming
tParam03.C:99 info message: 466 to test log trimming
tParam03.C:99 info message: 467 to test log trimming
tParam03.C:99 info message: 468 to test log trimming
tParam03.C:99 info message: 469 to test log trimming
tParam03.C:99 info message: 470 to test log trimming
tParam03.C:99 info message: 471 to test log trimming
tParam03.C:99 info message: 472 to test log trimming
tParam03.C:99 info message: 473 to test log trimming
tParam03.C:99 info message: 474 to test log trimming
tParam03.C:99 info message: 475 to test log trimming
tParam03.C:99 info message: 476 to test log trimming
tParam03.C:99 info message: 477 to test log trimming
tParam03.C:99 info message: 478 to test log trimming
tParam03.C:99 info message: 479 to test log trimming
tParam03.C:99 info message: 480 to test log trimming
tParam03.C:99 info message: 481 to test log trimming
tParam03.C:99 info message: 482 to test log trimming
tParam03.C:99 info message: 483 to test log trimming
tParam03.C:99 info message: 484 to test log trimming
tParam03.C:99 info message: 485 to test log trimming
tParam03.C:99 info message: 486 to test log trimming
tParam03.C:99 info message: 487 to test log trimming
tParam03.C:99 info message: 488 to test log trimming
tParam03.C:99 info message: 489 to test log trimming
tParam03.C:99 info message: 490 to test log trimming
tParam03.C:99 info message: 491 to test log trimming
tParam03.C:99 info message: 492 to test log trimming
tParam03.C:99 info message: 493 to test log trimming
tParam03.C:99 info message: 494 to test log trimming
tParam03.C:99 info message: 495 to test log trimming
tParam03.C:99 info message: 496 to test log trimming
tParam03.C:99 info message: 497 to test log trimming
tParam03.C:99 info message: 498 to test log trimming
tParam03.C:99 info message: 499 to test log trimming
tParam03.C:159 
test usage help: 

  Version: ParamTest 03

  -argfile      Name of file to read args from. (TEST_ARGFILE)
                '../data/param-03.args' 
  -help         show usage help. 'flag' 
  -version      show version and exit 'flag' 
  -gen-argfile  generate an args file. 'true' 
  -log-file     log file name. (LOG_FILE) '../data/param-03.log' 
  -log-mode     log open mode. (LOG_MODE) 'ios::out' 
  -log-prot     log protection flag. (LOG_PROT) '436' 
  -log-level    log output level. (LOG_LEVEL) 'TEST | INFO' 
  -log-filter   regex for filtering log enties (LOG_FILTER)
  -log-tee      Tee log output to cerr. (LOG_TEE) 'flag' 
  -log-show-time
                output time stamp with log entry. (LOG_SHOW_TIME) 'true' 
  -log-show-level
                output level with log entry. (LOG_SHOW_LEVEL) 'true' 
  -log-show-loc output source location with log entry (LOG_SHOWLOC) 'true' 
  -log-max      log file max size. (LOG_MAX) '10240' 
  -log-trim     log file trim size. (LOG_TRIM) '1024' 
  -error-log    error log file name. (ERROR_LOG)
  -error-log-level
                error log output levels. (ERROR_LOG_LEVEL) 'ERROR | WARN' 
  -string       argString test args 'test string' 
  -str          argStr test args 'test str' 
  -int          argInt test args '-123' 
  -uint         argInt unsigned test args '123' 
  -short        argShort test args '-456' 
  -ushort       argShort unsigned test args '456' 
  -long         argLong test args '-789' 
  -ulong        argLong unsigned test args '789' 
  -double       argDouble test args '10.10' 
  -bool         argBool test args 'true' 
  -flag         argFlag test args 'true' 
  -timet        argDateTime time_t test args '07/15/95 08:15:15' 
  -datetime     argDateTime DateTime test args '08/01/95 06:00:10' 
