TEST_DATA_DIR	= ../data
TEST_USER	= $(USER)
TEST_GROUP	= local
TEST_UID	= 50
TEST_GID	= 62


ARCH_INC 	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/test
CLUE_SRC_INC	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/src \
		  -I$(PRJ_TOPDIR)/src/arch/$(arch)/stdc++ \
		  -I$(PRJ_TOPDIR)/src/arch/Unix/src \
		  -I$(PRJ_TOPDIR)/src/arch/Clue1/src \
		  -I$(PRJ_TOPDIR)/src/arch/src \
		  -I$(PRJ_TOPDIR)/src/Clue 

CLUE_SRC_LDIR	= -L$(PRJ_TOPDIR)/src/Clue

ARCH_DEBUG_LIBS	=  -lGnuRegex # -lrwtool
ARCH_DEFAULT_LIBS = -lGnuRegex
# ARCH_LIBS	= -lpthreads
