.\" Man page for libClue C++ Utilitiy Classes, Functions & Macros
.\"
.\" Author:  Paul Houghton (paul_houghton@wcom.com)
.\" Created: 10/26/96
.\"
.\" $Id$
.\" 
.TH Clue 3 "" "10/26/1996" "Clue"
.SH NAME
Clue \- Common Library of Utilities & Etc. for C++
.SH DESCRIPTION
This library provides a wide varity of general purpose
class, functions and macros. They should be usefull for
any application developement effort that uses C++.
.SH CLASSES
.TP
ClassVersion(3)
Provides information about a class's version information that
is accessible at run time. (ClassVersion.hh)
.SH FUNCTIONS
.TP
Compare(3)
Compares two values of the same time and returns a value
that is 0, < 0 or > 0. (Compare.hh)
.SH FILES
libClue.a
.SH SEE ALSO
.SH AUTHOR
Paul Houghton (paul_houghton@wcom.com) /- 10/26/96
.\" $Log$
.\" Revision 1.1  1996/10/28 12:00:42  houghton
.\" Initial Version.
.\"