#
#
# Title:        Makefile.Test
# Project:	StlUtils
# Desc:
# 
#   
# 
# Notes:
# 
# Author:	Paul Houghton 719-527-7834 - (paul.houghton@wcom.com)
# Created:	07/18/97 06:44
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 

TEST_DATA_DIR	= ../data
TEST_USER	= $(shell /usr/xpg4/bin/id -u -n)
TEST_GROUP	= $(shell /usr/xpg4/bin/id -g -n)
TEST_UID	= $(shell /usr/xpg4/bin/id -u)
TEST_GID	= $(shell /usr/xpg4/bin/id -g)

ARCH_DEFINES	= -DSTLUTILS_TEST_NO_GROUPS=1
ARCH_INC 	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/test
STLUTILS_SRC_INC	= -I$(PRJ_TOPDIR)/src/arch/$(arch)/src 		\
		  -I$(PRJ_TOPDIR)/src/arch/Unix/src 		\
		  -I$(PRJ_TOPDIR)/src/arch/src 			\
		  -I$(PRJ_TOPDIR)/src/StlUtils 

STLUTILS_SRC_LDIR	= -L$(PRJ_TOPDIR)/src/StlUtils

ARCH_DEBUG_LIBS		= -lGnuRegex 
ARCH_DEFAULT_LIBS 	= -lGnuRegex

#
# $Log$
# Revision 6.1  2003/08/09 11:22:46  houghton
# Changed to version 6
#
# Revision 5.1  2000/05/25 10:33:21  houghton
# Changed Version Num to 5
#
# Revision 4.3  1997/12/20 16:10:46  houghton
# Chagned to get the user & group info from the os.
#
# Revision 4.2  1997/12/19 12:51:07  houghton
# Changed for asterope.jxn ids.
#
# Revision 4.1  1997/09/17 15:13:27  houghton
# Changed to Version 4
#
# Revision 3.3  1997/09/17 11:09:17  houghton
# Changed: renamed library to StlUtils.
#
# Revision 3.2  1997/08/18 10:30:58  houghton
# Changed uid and group (I really need a better solution to this).
#
# Revision 3.1  1997/07/25 12:26:21  houghton
# Changed version number to 3.
#
# Revision 1.1  1997/07/18 19:51:02  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:

