#
# Title:        Makefile
# Project:	StlUtils ()
# Desc:
# 
#   This is a 'convienance' Makefile. It is only to simplify
#   fixing compile errors. DO NOT add any more targets.
# 
# Notes:
# 
# Author:	Paul Houghton - (paul.houghton@mci.com)
# Created:	05/04/99 07:03
#
# Revision History: (See end of file for Revision Log)
#
#   $Author$ 
#   $Date$ 
#   $Name$ 
#   $Revision$ 
#   $State$ 
# 
#  $Id$ 
# 


debug:
	$(MAKE) -C ../../.. $@


#
# $Log$
# Revision 6.1  2003/08/09 11:22:46  houghton
# Changed to version 6
#
# Revision 5.3  2003/08/09 11:21:01  houghton
# Changed ver strings.
#
# Revision 5.2  2001/07/26 19:28:57  houghton
# *** empty log message ***
#
# Revision 5.1  2000/05/25 10:33:22  houghton
# Changed Version Num to 5
#
# Revision 4.1  1999/05/09 13:08:19  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:
