#
# Title:        Makefile
# Project:	StlUtils
# Desc:
# 
#   This is a 'convienance' Makefile. It is only to simplify
#   fixing compile errors. DO NOT add any more targets.
# 
# Notes:
# 
# Author:	Paul Houghton - (paul.houghton@wcom.com)
# Created:	05/04/99 07:03
#
# Revision History: (See end of file for Revision Log)
#
#   Last Mod By:    $Author$
#   Last Mod:	    $Date$
#   Version:	    $Revision$
#
#   $Id$
# 


debug:
	$(MAKE) -C ../../.. $@


#
# $Log$
# Revision 5.1  2000/05/25 10:33:22  houghton
# Changed Version Num to 5
#
# Revision 4.1  1999/05/09 13:08:19  houghton
# Initial Version.
#
#

# Local Variables:
# mode:makefile
# End:
