#
# -*- Makefile -*- for Clue src dir
#
# Author: Paul Houghton
#
# Created: 11/12/95
#
# $Id$
#

include Make/make.cfg.3.5

SUBDIRS = Clue

include Make/make.cfg.targets.3.5

#
# $Log$
# Revision 1.1  1995/11/12 17:50:43  houghton
# Initial Version.
#
#